- name: MSSQL AG refresh preparation
  hosts: "{{ ctrl_server | default('localhost') }}"
  gather_facts: false
  vars:
    mssql_refresh_use_cyberark: "{{ use_cyberark | default(true) }}"
    mssql_refresh_require_credentials: true
    mssql_refresh_backup_lookback_hours: "{{ backup_lookback_hours | default(72) }}"
    security_script_output: "{{ security_script_output | default(omit) }}"
  roles:
    - MsSQL_database_refresh
