
---
- hosts: "{{ ctrl_server }}"
  gather_facts: false

  tasks:
    - name: Execute AG rejoin workflow when required
      include_role:
        name: ag_resync_db
      when:
        - refresh_context.actions.rejoin_method | default('none') != 'none'
        - rejoin_ag | bool
        - Dest_ag_name != 'N/A'
