---
# --------------------------------------------------------------
# Task: Send Failure Email if restore script generation fails
# --------------------------------------------------------------
- name: Send failure email if restore script generation fails
  shell: |
      [string]$body=@'
          Destination Database Refresh Failed!
          
          **Failure Details:**
          - **Source Instance:** {{ src_instance }}
          - **Source Database:** {{ src_database }}
          - **Destination Instance:** {{ dest_instance }}
          - **Destination Database:** {{ dest_database }}
          - **Restore Type:** {{ restore_type }}
          - **Reason for Failure:** Failed to generate the restore script.
          - **Job ID - {{ tower_job_id }}**

          **Action Required:**
          Please check the logs for further details and take necessary corrective actions.
      '@
      
      $msg = New-Object Net.Mail.MailMessage
      $msg.From = "{{ ctrl_server }}@energytransfer.com"
      $msg.Subject = "🚨 URGENT: Database Refresh Failed - {{ dest_database }} from {{ src_database }}"
      $msg.Body = $body
      $msg.Priority = "High"

      $mailer = New-Object Net.Mail.SMTPClient("{{ smtp_server }}")
      
      $msg.To.Add("dlitissql@energytransfer.com")
      $mailer.Send($msg) 
  args:
      executable: pwsh
  delegate_to: localhost
  when: not restore_script_stat.stat.exists or restore_script_stat.stat.size == 0

- name: Stop the entire playbook if restore script is missing or empty
  meta: end_play
  when: not restore_script_stat.stat.exists or restore_script_stat.stat.size == 0

# --------------------------------------------------------------
# Additional Task: Send Failure Email if Database Refresh Fails
# --------------------------------------------------------------
- name: Send failure email if database refresh fails
  shell: |
      [string]$body=@'
          🚨 **Database Refresh Failed!** 🚨
          
          **Failure Details:**
          - **Source Instance:** {{ src_instance }}
          - **Source Database:** {{ src_database }}
          - **Destination Instance:** {{ dest_instance }}
          - **Destination Database:** {{ dest_database }}
          - **Restore Type:** {{ restore_type }}
          - **Job ID:** {{ tower_job_id }}
          
          **Error Logs:**
          --------------------------------------------------------------
          {{ restore_out.stderr | default('No error details available.') }}
          --------------------------------------------------------------
          
          **Action Required:**
          Please check the logs and investigate the error to resolve the issue.
      '@
      
      $msg = New-Object Net.Mail.MailMessage
      $msg.From = "{{ ctrl_server }}@energytransfer.com"
      $msg.Subject = "🚨 ALERT: Database Refresh Failed - {{ dest_database }} from {{ src_database }}"
      $msg.Body = $body
      $msg.Priority = "High"

      $mailer = New-Object Net.Mail.SMTPClient("{{ smtp_server }}")
      
      $msg.To.Add("dlitissql@energytransfer.com")
      $mailer.Send($msg) 
  args:
      executable: pwsh
  delegate_to: localhost
  when: restore_out.rc != 0