---
#Creates a Restore Script from Instance/DB
#Note needs to be passed Instance/DB
- name: Generate restore script from templates
  win_template:
    src: ../templates/sp_restore_gen.sql.j2
    dest: d:\downloads\ansible\gen_restore_{{srcdatabase}}.sql

- name: debug path to download
  debug: var=hostvars[source_host].downloadpath

- name: Execute gen restore script
  win_shell: |
        $ErrorActionPreference = "Stop";
        try{Import-Module SQLPS}
        catch{
          Add-PSSnapin SqlServerCmdletSnapin100
          Add-PSSnapin SqlServerProviderSnapin100
          }
         $server = "{{instance}}"
         $query = Get-Content 'D:\downloads\ansible\gen_restore_{{srcdatabase}}.sql' | Out-String
        Invoke-sqlcmd -Server $server -Query $query | Select-Object -ExpandProperty sqltext |
        Out-File -filepath "{{hostvars[source_host].downloadpath}}\restore_script_{{srcdatabase}}.sql"
  register: restore_script_{{srcdatabase}}
  no_log: true

