---
#Creates a Script of logins for a Instance/DB
#Note needs to be passed Instance/DB
- name: Generate login script from templates
  win_template:
    src: sp_script_login.sql.j2
    dest: d:\downloads\ansible\script_logins_{{srcdatabase}}.sql

- name: Execute gen logins script
  win_shell: |
        $ErrorActionPreference = "Stop";
        try{Import-Module SQLPS}
        catch{
          Add-PSSnapin SqlServerCmdletSnapin100
          Add-PSSnapin SqlServerProviderSnapin100
          }
         $server = "{{instance}}"
         $query = Get-Content 'D:\downloads\ansible\script_logins_{{srcdatabase}}.sql' | Out-String
        Invoke-sqlcmd -Server $server -Query $query | Select-Object -ExpandProperty sqltext |
        Out-File -filepath "{{hostvars[source_host].downloadpath}}\create_users_script_{{srcdatabase}}.sql"
  #register: logins_script_{{srcdatabase}}
  no_log: true
