#Check the current sql instances on a host
#Variable to only return instance that are online
- name: Check if online instances only to be reported
  set_fact:
     psScript: "get_instance_online.ps1"
  when: online_only

- name: Copy the PS script to host
  win_copy:
    src: "../files/{{psScript}}"
    dest: d:\downloads\ansible\

#Register the output [Instance Name(s)]
- name: Get sql instnace details
  win_command: powershell.exe -file "d:\downloads\ansible\{{psScript}}"
  register: inst_out

- name: Set variables for backslash processing
  set_fact:
    backslash_pattern: '\\\\+'
    single_backslash: '\\'

- name: Initialize the instances list properly
  set_fact:
    instances: []

- name: Collect and Clean SQL instances (Final Fix)
  set_fact:
    instances: >-
      {{ inst_out.stdout_lines
         | map('trim')
         | select('search', '^(?![\[\]])')
         | map('replace', '"', '')
         | map('regex_replace', ',\s*$', '')
         | map('regex_replace', backslash_pattern, single_backslash)
         | list
      }}

- debug:
    msg: "{{ instances }}"

- name: Loop Through Cleaned Instances
  debug:
    msg: "{{ item }}"
  loop: "{{ instances }}"
